name: workflow action file

on:
  push:
    branches: [ develop ]
  workflow_dispatch: #allows menaul trigger

jobs:
    prepair-release:
      runs-on: ubuntu-latest
      
      steps:
        - name: checkout repository
          uses: actions/checkout@v4

        - name: create and push replease branch
          env: 
            PATKEY: ${{secrets.PATKEY}}  
          run: |
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git checkout -b release/$(date +%Y-%m-%d)
            git push https://${{secrets.PATKEY}}}@github.com/prem381/workflow.git release/$(date +%Y-%m-%d)

    deploy-release:
      needs: prepair-release
      runs-on: ubuntu-latest       
      if: success()

      steps:
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: checkout repository
          env: 
            PATKEY: ${{secrets.PATKEY}}
          run: |
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git checkout main
            git merge release/$(date +%Y-%m-%d)
            git push https://${{secrets.PATKEY}}@github.com/prem381/workflow.git main


        - name: Create GitHub Release
          id: create_release
          uses: actions/create-release@v3
          with:
             tag_name: v1.0.${{ github.run_number }} # Dynamic version
             release_name: "Release v1.0.${{ github.run_number }}"
             body: "Automated monthly release for v1.0.${{ github.run_number }}"
             draft: false
             prerelease: false
