name: Git Workflow CI/CD
on:
  push:
    branches:
      - "feature/*"
jobs:
  test-feature:
    name: Test on Feature Branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        env:
        # allow github action to perform
          PATKEY: ${{secrets.PATKEY}} 

      - name: Set up Python (if applicable)
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          sudo apt update -y
          sudo apt install apache2 -y

    # If tests pass, merge to the test branch
      - name: Merge to Test Branch
        if: success()
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git checkout test
          git merge --no-ff $(git rev-parse --abbrev-ref HEAD) -m "Merging feature into test"
          git push origin https://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@github.com/prem381/workflow.git test

  test-test:
    name: Test on Test Branch
    needs: test-feature
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Test Branch
        uses: actions/checkout@v4
        with:
          ref: test 

    # If tests pass, merge to master
      - name: Merge to Master Branch
        if: success()
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git checkout master
          git merge --no-ff test -m "Merging test into master"
          git push origin https://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@github.com/prem381/workflow.git master

  test-master:
    name: Test on Master Branch
    needs: test-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Master Branch
        uses: actions/checkout@v4
        with:
          ref: master  

  schedule-release:
    name: Release Branch Update
    needs: test-master
    runs-on: ubuntu-latest
    if: github.event.schedule == '0 0 25 * *'
    steps:
      - name: Checkout Master Branch
        uses: actions/checkout@v4
        with:
          ref: master

      - name: Merge to Release Branch
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git checkout release
          git merge --no-ff master -m "Merging master into release on 25th"
          git push origin https://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@github.com/prem381/workflow.git release
