name: Master to Release Branch

on:
  schedule:
    - cron: "0 0 25 * *" # Runs at midnight UTC on the 25th of each month
  workflow_dispatch:

jobs:
  test-master:
    name: Test on Master Branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Master Branch
        uses: actions/checkout@v4
        with:
          ref: master

      - name: Run Tests
        run: |
          echo "Running tests..."
          # Add actual test commands (e.g., pytest)

      - name: Merge to Release Branch
        if: success()
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          git remote set-url origin https://${{ secrets.PATKEY }}@github.com/prem381/workflow.git
          git fetch origin

          if git ls-remote --heads origin release | grep release; then
            git checkout release
          else
            git checkout -b release
            git push origin release
          fi

          git merge --no-ff master -m "Merging master into release"
          git push origin release
