name: Main to Release Branch
on:
  workflow_run:
    workflows: ["Test to master"]
    types:
      - completed
    
  workflow_dispatch:

jobs:
  test-main:
    name: Test on Main Branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Main Branch
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Run Tests
        run: |
          echo "Running tests..."
          # Add actual test commands (e.g., pytest)

      - name: Merge to Release Branch
        if: success()
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          git remote set-url origin https://${{ secrets.PATKEY }}@github.com/prem381/workflow.git
          git fetch origin

          if git ls-remote --heads origin release | grep release; then
            git checkout release
          else
            git checkout -b release
            git push origin release
          fi

          git merge --no-ff release -m "Merging main into release"
          git push origin release
