name: Scheduled Release

on:
  schedule:
    - cron: '0 0 25 * *'  # Runs at 00:00 UTC on the 25th of every month

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Required for merging branches

      - name: Merge Master into Release
        if: github.event_name == 'schedule'
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git checkout master
          git pull origin master
          git checkout release
          git merge --no-ff master -m "Merging master into release on 25th"
          git push origin https://${secrets.PATKEY}@github.com/prem381/workflow.git release