name: Git Workflow CI/CD
on:
  push:
    branches:
      - "feature/*"
  workflow_dispatch:

jobs:
  test-feature:
    name: Test on Feature Branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        env:
        # allow github action to perform
          PATKEY: ${secrets.PATKEY} 

      - name: Set up Python (if applicable)
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

    # If tests pass, merge to the test branch
      - name: Merge to Test Branch
        if: success()
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          # fetch all branch
          git fetch origin
          # Check if 'test' branch exists, create if not
          if git rev-parse --verify origin/test >/dev/null 2>&1; then
          git checkout test
          else
          git checkout -b test
          git push origin test  # Push newly created branch to remote
          fi
          git merge --no-ff $(git rev-parse --abbrev-ref HEAD) -m "Merging feature into test"
          git push origin test

  test-test:
    name: Test on Test Branch
    needs: test-feature
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Test Branch
        uses: actions/checkout@v4
        with:
          ref: test
        env:
          # allow github action to perform
          PATKEY: ${secrets.PATKEY} 

    # If tests pass, merge to master
      - name: Merge to Master Branch
        if: success()
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git checkout master
          git merge --no-ff test -m "Merging test into master"
          git push origin https://${{ secrets.PATKEY }}@github.com/prem381/workflow.git master

  test-master:
    name: Test on Master Branch
    needs: test-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Master Branch
        uses: actions/checkout@v4
        with:
          ref: master
        env:
          # allow github action to perform
          PATKEY: ${secrets.PATKEY} 
  
    # If tests pass, merge to release
      - name: Merge to Master Branch
        if: success()
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git checkout master
          git merge --no-ff test -m "Merging test into master"
          git push origin https://${{ secrets.PATKEY }}@github.com/prem381/workflow.git master
  