name: Git Workflow CI/CD action1 file
on:
  push:
    branches:
      - "feature/*"
      - test
  workflow_dispatch:
jobs:
  test-feature:
    name: Test on Feature Branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Merge to Test Branch
        if: success()
        run: |
           git init
           git rempte add origin ....
           git remote set-url origin https://${{ secrets.PATKEY }}@github.com/prem381/workflow.git
           git clone https://github.com/prem381/workflow.git
           git fetch origin
           git checkout test
           git push origin test

---
name: Git Workflow CI/CD
on:
  workflow_dispatch:
  if:
   name: test-feature
     if: ${{ true }}
  schedule:
     - cron: "0 0 0 25 0 0"
