name: Git Workflow CI/CD
on:
  push:
    branches:
      - "feature/*"
      - test
  workflow_dispatch:

jobs:
  test-feature:
    name: Test on Feature Branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Merge to Test Branch
        if: success()
        run: |
          git config --global user.name "GitHub Actions"
       git config --global user.email "actions@github.com"
       